### ISSUE TITLE
Home directory aren't honored when created by Linux

### ISSUE THREAD

**Issue by bernardoVale** [bernardoVale/ansible-role-db2#13]
The code above makes impossible to create a user on `/db2/myuser` for example.

```
- name: Creating DB2 Instance Users
  user:
    name: "{{item.name}}"
    group: "{{item.group_name}}"
    password: ldUMKEu7/QCAY
    home: "/home/{{item.name}}"
    when: item.options is not defined or item.options.password is not defined
    with_items: db2_instances
```
