### ISSUE TITLE
Uid/gid random generated

### ISSUE THREAD

**Issue by bernardoVale** [bernardoVale/ansible-role-db2#15]
Cannot set uid and gid for multiple instances.

This [configuration](https://gist.github.com/bernardoVale/11516688fe8b5713136e0b05652dd395) would create three instances.

In this configuration we've set uid/gid manually for the first instance but not for the others. 

The user creation task:

```yaml
- name: Creating DB2 Instance Users - Custom home_dir
  user:
    name: "{{item.name}}"
    group: "{{item.group_name}}"
    password: "{{ item.password | default('ldUMKEu7/QCAY')}}"
    home: "{{ item.home_directory }}"
    gid: "{{ item.gid | default('543') }}"
    uid: "{{ item.uid | default('544') }}"
  with_items: "{{ db2_instances }}"
  when: item.home_directory is defined
```

Would translate into this:

```yaml
- name: Creating DB2 Instance Users - default
  user:
    name: "myinstan"
    group: "myinadm"
    password: "foo"
    home: "/home/myinstan"
    gid: 666
    uid: 667 
...
- name: Creating DB2 Instance Users - default
  user:
    name: "myinstan2"
    group: "myinadm2"
    password: "foo"
    home: "/home/myinstan2"
    gid: 543 # Default since not specified
    uid: 544 # Default since not specified
...
- name: Creating DB2 Instance Users - default
  user:
    name: "myinstan2"
    group: "myinadm2"
    password: "foo"
    home: "/home/myinstan2"
    gid: 543 # Default since not specified
    uid: 544 # Default since not specified
```

Assuming those gid/uid are not used by another user/group first and second tasks would succeed but not the third one since its using the same gid/uid as the second.

**Comment by bernardoVale** [comment]
Is not possible to set both uid and gid now. Research it's required

**Comment by OndrejHome** [comment]
Hi @bernardoVale, what exact problem is here?
Making a simple test with tasks below it seems that I can set uid and gid with multiple instances. Problem is if I don't specify uid/gid for more that one instance - it will fails as expected with multiple users/groups having same uid/gid - Is that the problem here or something else?

ansible 2.3.2.0

    ---
    - hosts: all
      remote_user: root
      vars:
        db2_instances:
          - name: test
            fenced_group_name: test
            group_name: test
            gid: 555
            uid: 666
          - name: test2
            fenced_group_name: test2
            group_name: test2
            gid: 444
            uid: 777
      tasks:
        - name: Creating DB2 Fenced Groups
          group:
            name: "{{item.fenced_group_name}}"
            state: present
            gid: "{{ item.gid | default('543') }}"
          with_items: "{{ db2_instances }}"
        - name: Creating DB2 Instance Users
          user:
            name: "{{item.name}}"
            group: "{{item.group_name}}"
            password: "{{ item.password | default('ldUMKEu7/QCAY')}}"
            home: "/home/{{item.name}}"
            uid: "{{ item.uid | default('543') }}"
          with_items: "{{ db2_instances }}"

**Comment by bernardoVale** [comment]
Yes @OndrejHome the problem is when you set gid/uid for one instance but don't set for others.

If you set gid/uid for all instances of `db2_instances` hash it will work fine:

```yaml
      db2_instances:
        - instance: "DB2INST"
          name: "myinstan" 
          group_name: "myinadm"
          fenced_username: "myfenc1"
          fenced_group_name: "myfadm1"
          gid: 555
          fenced_gid: 556
          uid: 555
          fenced_gid: 556
```
